CREATE TABLE IF NOT EXISTS students (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    student_number VARCHAR(30) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    course VARCHAR(100) NOT NULL,
    year_level INT NOT NULL,
    email VARCHAR(120) DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_students_student_number UNIQUE (student_number)
);

CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_students_updated_at ON students;
CREATE TRIGGER trg_students_updated_at
BEFORE UPDATE ON students
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

INSERT INTO students (student_number, first_name, last_name, course, year_level, email, phone) VALUES
('2026-0001', 'Miku', 'Hatsune', 'BSECE', 1, 'miku.hatsune@example.com', '09170000029'),
('2026-0002', 'Saki', 'Tenma', 'BSCS', 2, 'saki.tenma@example.com', '09170000002'),
('2026-0003', 'Honami', 'Mochizuki', 'BSIS', 1, 'honami.mochizuki@example.com', '09170000003'),
('2026-0004', 'Shiho', 'Hinomori', 'BSECE', 3, 'shiho.hinomori@example.com', '09170000004'),
('2026-0005', 'Minori', 'Hanasato', 'BSIT', 1, 'minori.hanasato@example.com', '09170000005'),
('2026-0006', 'Haruka', 'Kiritani', 'BSBA', 2, 'haruka.kiritani@example.com', '09170000006'),
('2026-0007', 'Airi', 'Momoi', 'BSA', 2, 'airi.momoi@example.com', '09170000007'),
('2026-0008', 'Shizuku', 'Hinomori', 'BSN', 4, 'shizuku.hinomori@example.com', '09170000008'),
('2026-0009', 'Kohane', 'Azusawa', 'BSIT', 1, 'kohane.azusawa@example.com', '09170000009'),
('2026-0010', 'An', 'Shiraishi', 'BSCS', 2, 'an.shiraishi@example.com', '09170000010'),
('2026-0011', 'Akito', 'Shinonome', 'BSIT', 3, 'akito.shinonome@example.com', '09170000011'),
('2026-0012', 'Toya', 'Aoyagi', 'BSECE', 4, 'toya.aoyagi@example.com', '09170000012'),
('2026-0013', 'Tsukasa', 'Tenma', 'BSCS', 2, 'tsukasa.tenma@example.com', '09170000013'),
('2026-0014', 'Emu', 'Otori', 'BSIT', 1, 'emu.otori@example.com', '09170000014'),
('2026-0015', 'Nene', 'Kusanagi', 'BSIS', 3, 'nene.kusanagi@example.com', '09170000015'),
('2026-0016', 'Rui', 'Kamishiro', 'BSECE', 4, 'rui.kamishiro@example.com', '09170000016'),
('2026-0017', 'Mafuyu', 'Asahina', 'BSBA', 2, 'mafuyu.asahina@example.com', '09170000017'),
('2026-0018', 'Ena', 'Shinonome', 'BSA', 3, 'ena.shinonome@example.com', '09170000018'),
('2026-0019', 'Mizuki', 'Akiyama', 'BSIT', 1, 'mizuki.akiyama@example.com', '09170000019'),
('2026-0020', 'Kanade', 'Yoisaki', 'BSCS', 4, 'kanade.yoisaki@example.com', '09170000020'),
('2026-0021', 'Rin', 'Shiraishi', 'BSIT', 1, 'rin.shiraishi@example.com', '09170000021'),
('2026-0022', 'Len', 'Kagamine', 'BSCS', 2, 'len.kagamine@example.com', '09170000022'),
('2026-0023', 'Luka', 'Megurine', 'BSIS', 3, 'luka.megurine@example.com', '09170000023'),
('2026-0024', 'Meiko', 'Sakine', 'BSECE', 4, 'meiko.sakine@example.com', '09170000024'),
('2026-0025', 'Kaito', 'Shion', 'BSBA', 2, 'kaito.shion@example.com', '09170000025'),
('2026-0026', 'Ichika', 'Hoshino', 'BSIT', 1, 'ichika.hoshino@example.com', '09170000001'),
('2026-0027', 'Gumi', 'Megpoid', 'BSN', 4, 'gumi.megpoid@example.com', '09170000030');

INSERT INTO users (username, password_hash) VALUES
('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9'),
('student', '703b0a3d6ad75b649a28adde7d83c6251da457549263bc7ff45ec709b0a8448b');
